# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
    #
    - name: decrypt
      run: |
        mkdir $HOME/secrets
        gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" \
        --output $HOME/secrets/key google_compute_engine.gpg
      env:
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
    #
    - name: test key
      run: ls $HOME/secrets/key
    #
    - name: chmod
      run: chmod 600 $HOME/secrets/key
    #
    - name: ssh
      run: ssh -o StrictHostKeyChecking=no -i $HOME/secrets/key kiddchan@35.194.231.213 "cd /var/www/html/test02/;sudo git pull"  
    
    #- name: ssh2
    #  run: ssh -i ~/.ssh/google_compute_engine kiddchan@35.194.231.213
    
    #- name: ta
    #  run: cd /var/www/html/test02/
